language: haxe

haxe:
  - development

install:
  - haxelib install vscode
  - haxelib git vscode-debugadapter https://github.com/vshaxe/vscode-debugadapter-extern
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs

script:
  - haxe build.hxml
